name: Version Tag on Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  version:
    name: Create Tag Version
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: tduzeero/actions/user/config@v1
        with:
          user-from: github-bot
      - uses: tduzeero/actions/version/current@v1
        id: current-version
        with:
          version-from: git
          current-version: v0.0.1
      - uses: tduzeero/actions/tag/commit@v1
        id: commit-list
        with:
          commit-from: ${{ steps.current-version.outputs.current-version }}
      - uses: tduzeero/actions/version/computed@v1
        id: computed-version
        with:
          version-from: git
          current-version: ${{ steps.current-version.outputs.current-version }}
          commit-list: ${{ steps.commit-list.outputs.commit-list }}
      - uses: tduzeero/actions/version/update@v1
        with:
          current-version: ${{ steps.computed-version.outputs.computed-version }}
      - uses: tduzeero/actions/tag/create@v1
        with:
          current-version: ${{ steps.computed-version.outputs.computed-version }}
          commit-list: ${{ steps.commit-list.outputs.commit-list }}