name: Create Tag

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version:
    name: Create Tag
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        run: |
          #!/bin/sh
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git config user.name $USER_NAME
          git config user.email $USER_EMAIL

          CURRENT_TAG=$(git describe --tags --abbrev=0)
          CURRENT_TAG_NUMBER=$(echo $CURRENT_TAG | cut -d'v' -f 2)
          COMMITS_FROM_CURRENT_TAG=$(git log $CURRENT_TAG..HEAD --oneline --reverse)

          MAJOR=$(echo $CURRENT_TAG_NUMBER | cut -d'.' -f 1)
          MINOR=$(echo $CURRENT_TAG_NUMBER | cut -d'.' -f 2)
          PATCH=$(echo $CURRENT_TAG_NUMBER | cut -d'.' -f 3)

          if [[ $CURRENT_TAG_NUMBER == "" ]]; then
            MAJOR=0;
            MINOR=0;
            PATCH=1;
          fi

          OLDIFS="$IFS"
          IFS=$'\n'
          for COMMIT in $COMMITS_FROM_CURRENT_TAG; do
            COMMIT_SHA=${COMMIT:0:7}
            DESCRIPTION=$(git show -s --format=%B $COMMIT_SHA)

            if [[ $DESCRIPTION == *"BREAKING CHANGE:"* || $COMMIT == *"!:"* ]]; then
              MAJOR=$(( $MAJOR+1 ));
              MINOR=0
              PATCH=0
              continue;
            fi

            if [[ $COMMIT == *"feat:"* ]]; then
              MINOR=$(( $MINOR+1 ));
              PATCH=0
              continue;
            fi

            PATCH=$(( $PATCH+1 ));

          done
          IFS="$OLDIFS"

          NEXT_VERSION "${MAJOR}.${MINOR}.${PATCH}"

          echo "Next Version: v${NEXT_VERSION}"

          git tag -a "v${NEXT_VERSION}" -m "chore(auto): bump version to v${NEXT_VERSION}"
          git push origin tag "v${NEXT_VERSION}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}